In [1]:
import numpy as np
from converter import *
%load_ext line_profiler

In [4]:

x = np.linspace(-5,5,100)
p = np.linspace(-5,5,100)

n_cutoff = 5
one = np.zeros(n_cutoff).reshape(n_cutoff,1)
one[1]=1
rho = one @ one.T
print(rho)

%timeit wigner_from_density(rho, x, p)

%lprun -f  W_mn wigner_from_density(rho, x, p)

# X,Y = np.meshgrid(x,p)
# plt.imshow(W, cmap="RdBu_r")
# plt.show()

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
515 ms ± 2.87 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Timer unit: 1e-07 s

Total time: 1.16532 s
File: c:\Users\romjer\Documents\PhD\Cours\SCIQIS\Wigner-functions\converter.py
Function: W_mn at line 32

Line #      Hits         Time  Per Hit   % Time  Line Contents
    32                                           def W_mn(x,p,m,n):
    33         1        233.0    233.0      0.0      vectorized_apply = np.vectorize(lambda f, p: f(p))
    34         1      29789.0  29789.0      0.3      a = 1/np.pi*np.exp(-x**2-p**2)
    35         1      60535.0  60535.0      0.5      b = (-1)**n*(x-1j*p)**(m-n)
    36         1      99550.0  99550.0      0.9      c = np.sqrt(2**abs(m-n)*factorial(n,exact=True)/factorial(m,exact=True))
    37         1    4219940.0    4e+06     36.2      dbis = mygenlaguerre(n,abs(m-n))
    38         1    7214795.0    7e+06     61.9      d = vectorized_apply(dbis,2*x**2+2*p**2)
    39         1      28374.0  28374.0      0.2      return a*b*c*d

In [4]:
x = np.linspace(-5,5,100)
p = np.linspace(-5,5,100)

n_cutoff = 10
one = np.zeros(n_cutoff).reshape(n_cutoff,1)
one[1]=1
rho = np.random.rand(10,10)
rho = rho/np.linalg.norm(rho)
print(rho)

%timeit wigner_from_density(rho, x, p)

%lprun -f  W_mn wigner_from_density(rho, x, p)

%timeit wigner_from_density2(rho, x, p)

%lprun -f  W_mn2 wigner_from_density2(rho, x, p)

[[0.17639058 0.04623799 0.04908614 0.10940379 0.08194804 0.0703883
  0.08471434 0.00903552 0.06461318 0.13380712]
 [0.00680541 0.00608076 0.04614849 0.04508721 0.00809849 0.15221151
  0.09351517 0.0468337  0.04754363 0.02179907]
 [0.13764858 0.03277814 0.14894832 0.17601159 0.16057922 0.01373565
  0.09454558 0.00286514 0.07188063 0.06932301]
 [0.04207172 0.09475837 0.16983878 0.02547564 0.04539938 0.1585488
  0.09235856 0.15856689 0.16174023 0.01824765]
 [0.04323801 0.05188413 0.03912857 0.11844703 0.07654739 0.15990529
  0.12450929 0.00716134 0.09795922 0.13099654]
 [0.08740248 0.09262769 0.07265287 0.16942997 0.02796887 0.14501764
  0.05843604 0.16684192 0.07751765 0.17024333]
 [0.0252511  0.09012573 0.05882389 0.00554049 0.12956159 0.10741855
  0.0735993  0.17605317 0.05411878 0.13104454]
 [0.05264763 0.00192214 0.11791865 0.00259088 0.12246609 0.14274988
  0.14106683 0.11996568 0.12621974 0.00738829]
 [0.08983935 0.13573664 0.06816496 0.10269116 0.12711259 0.00524936
  0.10847056 0

Timer unit: 1e-07 s

Total time: 6.39334 s
File: c:\Users\romjer\Documents\PhD\Cours\SCIQIS\Wigner-functions\converter.py
Function: W_mn2 at line 83

Line #      Hits         Time  Per Hit   % Time  Line Contents
    83                                           def W_mn2(x,p,m,n):
    84         1        346.0    346.0      0.0      vectorized_apply = np.vectorize(lambda f, p: f(p))
    85         1     144777.0 144777.0      0.2      a = 1/np.pi*np.exp(-x**2-p**2)
    86         1     290875.0 290875.0      0.5      b = (-1)**n*(x-1j*p)**(m-n)
    87         1     545742.0 545742.0      0.9      c = np.sqrt(2**abs(m-n)*factorial(n,exact=True)/factorial(m,exact=True))
    88         1   62828967.0    6e+07     98.3      dbis = mygenlaguerre2(n,abs(m-n),x,p)
    89                                               # d = vectorized_apply(dbis,2*x**2+2*p**2)
    90         1     122740.0 122740.0      0.2      return a*b*c*dbis

In [3]:
x = np.linspace(-5,5,100)
p = np.linspace(-5,5,100)

n_cutoff = 5
one = np.zeros(n_cutoff).reshape(n_cutoff,1)
one[1]=1
n = np.arange(100, dtype=np.int16)
m = np.arange(100, dtype=np.int16)
rho = np.random.rand(len(n),len(n))
rho = rho/np.linalg.norm(rho)
print(rho)

W = wigner_from_density(rho, x, p)
rrr = density_from_wigner(W,n,m)

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
704 ms ± 48 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Timer unit: 1e-07 s

Total time: 1.8079 s
File: c:\Users\romjer\Documents\PhD\Cours\SCIQIS\Wigner-functions\converter.py
Function: mygenlaguerre at line 7

Line #      Hits         Time  Per Hit   % Time  Line Contents
     7                                           def mygenlaguerre(n,m,x,p):
     8                                                   # Loop over each pair of n and alpha
     9         1         79.0     79.0      0.0      results = np.empty(n.shape)
    10         1          5.0      5.0      0.0      computed_polynomials = {}
    11         1          2.0      2.0      0.0      computed_axis = {}
    12                                               
    13                                               # Loop over each pair of n and alpha
    14    250001    3028502.0     12.1     16.8      for index in np.ndindex(n.shape):
    15    250000     787344.0      3.1      4.4          n_val = n[index]
    16    250000     693862.0      2.8      3.8          alpha_val = m[in